VERSION 3.11.0 >> Camaeu : Intgration des commandes  - Intgration des fichiers Camaeu   - Connexion FTP   - Lecture du fichier zip   - Mappage des donnes sur les tables de la base   - Traitements spcifiques aprs intgration
>> Camaeu : Administration
 - Gestion des fichiers de bases
  - Produits
  - Centrales
  - Paramtres
  - Pays
  - Villes
 
>> Camaeu : Consultation commandes
 - Consultation des commandes
   - Grille principale
 - Dtail d'une commande
 - Actions possibles sur la commande depuis le dtail (Annulations, Modif quantit...)

 
>> Camaeu : Base des faonniers
 - Gestion des faonniers
  - Consultation
- Ajout / Modif / Suppression de fiches
- Intgration automatique des faonniers depuis les fichiers d'entres.

 
>> Camaeu : Fichiers de production
 - Gnration des fichiers de production (2 formats)
  2 formats de fichier de production selon le mode d'intgration :
  - Intgration automatique
  - Saisie manuelle des commandes.

 
>> Camaeu : Bon de prparation
 - Impression des Bons de prparation

 
>> Camaeu : Bon de livraison
 - Impression des BL + gnration du fichier PICK

 
>> Camaeu : Statistique
 - Mise en place des diffrentes statistiques

 
>> Camaeu : Etats de fin de mois
 - Gnration des tats de fin de mois
  - format PDF
  - format XLS
 
>> Camaeu : Validation des commandes
 - Validation des commandes par les faonniers
  - Email d'avertissement
- Validation / Refus des commandes
- Possibilit de modifier deux paramtres sur les commandes.

 
>> Camaeu : Documentation
 - Documentation Camaeu

 
>> I18N : Gnral
 - Traduire la lgende en allemand
  La lgende des icones pour la consultation de commande n'a pas t traduite.

 
>> Tape  l'oeil : Annulations
 - Annulation de commande du 26/05
  pour le fournisseur 999999.

 
>> OKADI : Consultation commandes
 - Vue dans le log : Erreur sur l'affichage du rcapitulatif par produit
  Erreur releve dans le log :

2010-05-31 11:49:47,605 ERROR managers.CommandesManager       - Erreur consitution des lignes rcapitulatives par produit pour une            commande (dossier OKAIDI :
fr.microtec.db.QueryException: Field suppl does not exist!

(Couvert par votre maintenance)