VERSION 5.95.0 >> Devanlay : Bon de livraison  - Envoi des BL par email   - Lors de la g�n�ration des bons de livraisons, envoyer � l'email de l'adresse de livraison le BL au format PDF en pi�ce jointe. - Si la livraison est accompagn�e d'information de tracking, on les fera figurer dans le message du mail.
 - Afficher mati�re sur les BL et BL partielles
  Ajouter une colonne pour y afficher la mati�re.

 
>> Monoprix : Saisie de commandes
 - Controle sur la saisie du prix
  Dans le formulaire de saisie de commande, controler que les informations de la zone prix soient bien constitu�s de caract�res num�riques ainsi que du "." (point) ou "," (virgule)

 
>> Base des fa�onniers
 - �No address is assigned to the order!�
  Je vous copie le email re�u:
Please be informed that recently we are facing problem in uploading order. Here in Bangladesh we are working with several Buying houses who have more than two or three factories. When we type the vendor code on supplier address box. Artemis shows a chart of all of the vendors under that code. But unfortunately the chart is of vendors is partially hidden behind a box named �No address is assigned to the order!�. For an example when we type vendor code 1284. It showes 5 factory names under that code like below screen shot. But unfortunately two factories are covered under the above mentioned box. Here the hidden factores are 1284 � PADMA TEXTILES � SATURN  &  1284 � PADMA TEXTILES SOUTHERN. Now when we need to select 1284 � PADMA TEXTILES � SATURN  we become confused whether it exists or not. Now Please solve the probelm thus uploading oreder will be easier for us. 

 
>> G�n�ral
 - M�moriser le nom du navigateur
  Lors de la connexion des utilisateurs � Art�mis, m�moriser en meme temps que l'heure et le login de connexion (table USERS_HISTO) le nom du navigateur utilis�.

 
>> Devanlay : Administration
 - Am�nagements sur les produits
  Ajouter une zone taille �tiquette (libell� sur 250 caract�res)
Dans la fiche mati�re, affecter le libell� directement depuis l'indication sur la fiche produit.

 
>> Tape � l'oeil : G�n�ral
 - Envoi automatis� d'un �tat reprenant les actions de la journ�e
  Le client souhaite recevoir d'Art�mis un fichier XLS tous les soirs � 23h00 avec 3 onglets :
-          Onglet1 : la liste des commandes que nous avons r�ceptionn�es ce jour
-          Onglet2 : la liste des commandes que nous avons mises en production ce jour
-          Onglet3 : la liste des commandes que nous avons exp�di�es ce jour

Ne pas faire figurer les commandes annul�es.

 
>> Devanlay :
 - Etat de fin de mois
  Faire l'export Excel.

 
>> Devanlay : Statistique
 - Devanlay : Statistique 13
  On garde pour l'instant la Statistique 12
Une Statistique 13 avec :
Par commande :
- La date de commande client
- La date de la commande � l�unit� de production
- La date de livraison confirm�e par l�unit� de production
- La date de livraison confirm�e au client.


 
>> Transporteur
 - Am�lioration du tracking
  Cette modification � pour objectif d'armoniser les libell�s de tracking.

Ajout d'un nouveau champ "tracking" avec pour valeur "Oui" ou "Non".
Ce champ s'il est � "Oui", donnera la possibilit� de saisir l'url de tracking. Ceci �vitera d'avoir des urls de tracking "sans url de tracking" ou vide.

Avec les modifications du dossier Devanlay, nous envoyons maintenant les urls de tracking par mail avec le BL � l'adresse mail de destination.



 
>> I18N : G�n�ral
 - Import des nouvelles traductions
  Importer les nouvelles traductions � Art�mis.

 
>> MIM : Transcodage
 - Transcoder les commandes d'un fichier Excel
  Transcoder les produits � STICKER_BIJ_LUN � en  � STICKER ACC � 

 
>> Jennyfer : Fichiers de validation
 - Erreur sur cr�ation du fichier de validation
  Erreur vue dans le log :
net.sf.jasperreports.engine.JRException: Byte data not found at location : C:\Users\JulienG\Desktop\Triangle 2 pour 9.99.png

 
>> Pimkie : Int�gration des commandes
 - Tester l'import d'un fichier
  - Int�grer le fichier 
- Donner le fichier de prod � Laurent pour voir ce qu'en ressort Art�mis.

 
>> Phildar : Saisie de commandes
 - Pouvoir faire r�f�rence aux commandes archiv�es
  Actuellement, il n'est pas possible de saisir des vignettes pour une commande archiv�e.
Il faut retirer cette condition pour pouvoir le faire.

 
>> Promod : Administration
 - Augmenter la capacit� de la zone des clients PICK
  Message de Laurent :
Nous avons besoin de plus de place pour la liste des usines dans la fiche utilisateur Promod : LI FUNG ALL

 
>> Devanlay : Fichiers de production
 - Ajouter toutes les mati�res valid�es avec quantit� � 0
  Lors de la cr�ation du fichier de production, dans la table PRINT, ajouter toutes les mati�res valid�es avec quantit� = 0 apr�s les lignes li�es aux commandes.